### ISSUE TITLE
Cannot combine led and saveConfig keys

### ISSUE THREAD

**Issue by leijou** [ohmtech-io/uThingVOC#2]
Firmware: 1.2.1

The config fails to apply when both `led` and `saveConfig` are included in the same message to the sensor. Settings are not applied and the status response is not triggered.

Fails: `{"led": false, "reportingPeriod": 3, "format": "json", "saveConfig": true}`

Works: `{"led": false, "reportingPeriod": 3, "format": "json"}`
Works: `{"reportingPeriod": 3, "format": "json", "saveConfig": true}`

**Comment by damancusonqn** [comment]
Fixed: The issue was related to the JSON string length (was limited to 64 bytes which is the maximum Bulk transfer size for USB Full speed). Now it parses longer objects (limit set to 255 characters) detecting multiple bulk transfers to accommodate for a higher number of tokens.
